sudo: required
dist: trusty

script:
  - bash -xve ./test/travis_ros_install.bash
<<<<<<< HEAD
#  - source ~/catkin_ws/devel/setup.bash
#  - bash -xve ./test/travis_package_make.bash
#  - source ~/catkin_ws/devel/setup.bash
#  - bash -xve ./test/travis_prepare_dummy_files.bash
#  - rostest pimouse_ros test.launch
=======
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
  - source ~/catkin_ws/devel/setup.bash
#  - bash -xve ./test/travis_prepare_dummy_files.bash
  - rostest pimouse_ros test.launch
>>>>>>> cd9d02ad2a632a9da1f4801364b9aeb54d0ed1c0
